### ISSUE TITLE
Feature request: Limit grid to parent container

### ISSUE THREAD

**Issue by ndabAP** [dattn/dnd-grid#11]
Currently, you can drag an element outside of a container. It would be nice to limit the allowed movement to the parent container.

**Comment by dattn** [comment]
How would you limit the grid ?

-  By setting a `max column count` as property
-  dynamically by parent node size `maxColcount = Math.floor(parentSize / gridWidth)`
But what to do with the boxes who are outside of the limits ? What should be done on resize ?
