### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by 0SilentFox0** [dattn/dnd-grid#52]
Is there Vue 3 support? When I install plugin I get errors like "selfHook.bind is not a function"
But when i install it in Vue2 the are no problems

**Comment by Aterr** [comment]
I guess this repo is abandoned.

**Comment by dattn** [comment]
I migrated to vue 3 today.

Use the npm next tag:
`npm i @dattn/dnd-grid@next`

https://github.com/dattn/dnd-grid/tree/next
