### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by mattheww-skyward** [dattn/dnd-grid#53]
Hi! This library is great, it's the only one I've found that uses native CSS grids. However, I'm not able to use it without a license - could you please add one to the repo to clarify how it may be used? I'm interested in using it in a commercial product, so I'd love it if it were a permissive license, but I'd understand either way and I don't want to pressure you.

For my use case, I'm planning to port it to typescript and add min/max resizing limits. I'd be happy to contribute these upstream if you're interested.

Thanks very much!

**Comment by dattn** [comment]
Thank you for the nice feedback.
I've put the whole project under the MIT license.
